### PR TITLE
Fix typos and apply C4LJ style for citations

### PR DESCRIPTION
**Pull request by dltj**
Looks very good. Fascinating to read; I had to keep going backwards with an editor's eye as I got engrossed in the content.

This pull request fixes some typos and puts the references into the Code4Lib standard. The latter messes up the automated processing of your Markdown flavor. If that is of concern, maybe I can make a separate branch with those changes and apply them myself before copying and pasting the HTML into WordPress.

Also, I assumed the IBM research about the amount of digital content created in a day was the Ainsworth _et al_ citation.  There was no explicit citation in the original text and it seems to make sense.

### CODE REVIEW

**Comment by ianmilligan1** [comment]
Aye, I would cite that as:

> IBM Research. “What is Big Data?” http://www-01.ibm.com/software/data/bigdata/what-is-big-data.html/. Accessed 29 March 2016.

If we merge, I can just do a quick commit to fix that citation.

**Comment by dltj** [comment]
If you could merge what is there now, then fix the citation, that would be great.  If the Ainsworth citation doesn't go with the data size quote, then I don't see where it was used.  (Maybe it was part of an earlier draft and the citation didn't get removed from the reference list?)

My plan was to copy the HTML from the MacDown editor and paste it into WordPress.  That is probably the path of least resistance.  Let's try that before creating the separate pandoc derivative.

**Comment by dltj** [comment]
Yup!  I think I can do that.  Copy and paste HTML from the article itself, no?  ;-)

**Comment by ianmilligan1** [comment]
Great! Thanks @dltj – I'm really, really looking forward to seeing this in C4L, and your help is very much appreciated with this. Let us know if we can be of any help with this.

**Pull request merged**
